# cloud build creation has been referred from : "https://cloud.google.com/build/docs/configuring-builds/create-basic-configuration"
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/csci-5408-new/k1/app:${SHORT_SHA}",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/csci-5408-new/k1/app:${SHORT_SHA}",
      ]

  - name: "gcr.io/cloud-builders/gke-deploy"
    id: "Deployment"
    args:
      [
        "run",
        "--filename=config.yaml",
        "--image=us-east1-docker.pkg.dev/csci-5408-new/k1/app:${SHORT_SHA}",
        "--location=us-east1-b",
        "--cluster=gke-1",
      ]

images:
  - us-east1-docker.pkg.dev/csci-5408-new/k1/app:${SHORT_SHA}