apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bhavisha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1
  labels:
    app: container1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      name: container1-pods
      labels:
        app: container1
    spec:
      containers:
        - name: container1-node
          image: us-east1-docker.pkg.dev/csci-5408-new/k1/app
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: myvolume
              mountPath: "/Bhavisha_PV_dir"
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: bhavisha

---
apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  selector:
    app: container1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000