apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bhavisha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2
  labels:
    app: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      name: container2-pods
      labels:
        app: container2
    spec:
      containers:
        - name: container2-node
          image: us-east1-docker.pkg.dev/csci-5408-new/k2/app
          ports:
            - containerPort: 6001
          volumeMounts:
            - name: myvolume
              mountPath: "/Bhavisha_PV_dir"
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: bhavisha

---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000